# Add your sponsor usernames below. Uncomment or add as needed.
github: [webxbeyond]
# patreon: your-patreon-username
open_collective: webxbeyond
# ko_fi: your-kofi-username
# tidelift: your-tidelift-platform-name
# community_bridge: your-community-bridge-project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# custom: ['https://your-custom-sponsor-link.com']
